// Package delivery_sdk provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.10.1 DO NOT EDIT.
package delivery_sdk

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"net/url"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetDeliveryJob request
	GetDeliveryJob(ctx context.Context, deliveryJobUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostJobCancelled request with any body
	PostJobCancelledWithBody(ctx context.Context, deliveryJobUuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostJobCancelled(ctx context.Context, deliveryJobUuid openapi_types.UUID, body PostJobCancelledJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDeliveryJobCurrentCourier request
	GetDeliveryJobCurrentCourier(ctx context.Context, deliveryJobUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateOpenRobotLidCommand request with any body
	CreateOpenRobotLidCommandWithBody(ctx context.Context, deliveryJobUuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateOpenRobotLidCommand(ctx context.Context, deliveryJobUuid openapi_types.UUID, body CreateOpenRobotLidCommandJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostOrderDroppedOff request with any body
	PostOrderDroppedOffWithBody(ctx context.Context, deliveryJobUuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostOrderDroppedOff(ctx context.Context, deliveryJobUuid openapi_types.UUID, body PostOrderDroppedOffJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostOrderPickedUp request with any body
	PostOrderPickedUpWithBody(ctx context.Context, deliveryJobUuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostOrderPickedUp(ctx context.Context, deliveryJobUuid openapi_types.UUID, body PostOrderPickedUpJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetOrderByExternalId request
	GetOrderByExternalId(ctx context.Context, externalId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateOrder request with any body
	CreateOrderWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateOrder(ctx context.Context, body CreateOrderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetOrder request
	GetOrder(ctx context.Context, orderUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetJobsForOrder request
	GetJobsForOrder(ctx context.Context, orderUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RequestQuote request with any body
	RequestQuoteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RequestQuote(ctx context.Context, body RequestQuoteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SetWebhooks request with any body
	SetWebhooksWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SetWebhooks(ctx context.Context, body SetWebhooksJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetDeliveryJob(ctx context.Context, deliveryJobUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDeliveryJobRequest(c.Server, deliveryJobUuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostJobCancelledWithBody(ctx context.Context, deliveryJobUuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostJobCancelledRequestWithBody(c.Server, deliveryJobUuid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostJobCancelled(ctx context.Context, deliveryJobUuid openapi_types.UUID, body PostJobCancelledJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostJobCancelledRequest(c.Server, deliveryJobUuid, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDeliveryJobCurrentCourier(ctx context.Context, deliveryJobUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDeliveryJobCurrentCourierRequest(c.Server, deliveryJobUuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateOpenRobotLidCommandWithBody(ctx context.Context, deliveryJobUuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateOpenRobotLidCommandRequestWithBody(c.Server, deliveryJobUuid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateOpenRobotLidCommand(ctx context.Context, deliveryJobUuid openapi_types.UUID, body CreateOpenRobotLidCommandJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateOpenRobotLidCommandRequest(c.Server, deliveryJobUuid, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostOrderDroppedOffWithBody(ctx context.Context, deliveryJobUuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostOrderDroppedOffRequestWithBody(c.Server, deliveryJobUuid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostOrderDroppedOff(ctx context.Context, deliveryJobUuid openapi_types.UUID, body PostOrderDroppedOffJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostOrderDroppedOffRequest(c.Server, deliveryJobUuid, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostOrderPickedUpWithBody(ctx context.Context, deliveryJobUuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostOrderPickedUpRequestWithBody(c.Server, deliveryJobUuid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostOrderPickedUp(ctx context.Context, deliveryJobUuid openapi_types.UUID, body PostOrderPickedUpJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostOrderPickedUpRequest(c.Server, deliveryJobUuid, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetOrderByExternalId(ctx context.Context, externalId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetOrderByExternalIdRequest(c.Server, externalId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateOrderWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateOrderRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateOrder(ctx context.Context, body CreateOrderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateOrderRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetOrder(ctx context.Context, orderUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetOrderRequest(c.Server, orderUuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetJobsForOrder(ctx context.Context, orderUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetJobsForOrderRequest(c.Server, orderUuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RequestQuoteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRequestQuoteRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RequestQuote(ctx context.Context, body RequestQuoteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRequestQuoteRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SetWebhooksWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetWebhooksRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SetWebhooks(ctx context.Context, body SetWebhooksJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetWebhooksRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetDeliveryJobRequest generates requests for GetDeliveryJob
func NewGetDeliveryJobRequest(server string, deliveryJobUuid openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "delivery_job_uuid", runtime.ParamLocationPath, deliveryJobUuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/delivery-jobs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostJobCancelledRequest calls the generic PostJobCancelled builder with application/json body
func NewPostJobCancelledRequest(server string, deliveryJobUuid openapi_types.UUID, body PostJobCancelledJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostJobCancelledRequestWithBody(server, deliveryJobUuid, "application/json", bodyReader)
}

// NewPostJobCancelledRequestWithBody generates requests for PostJobCancelled with any type of body
func NewPostJobCancelledRequestWithBody(server string, deliveryJobUuid openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "delivery_job_uuid", runtime.ParamLocationPath, deliveryJobUuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/delivery-jobs/%s/commands/cancel", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetDeliveryJobCurrentCourierRequest generates requests for GetDeliveryJobCurrentCourier
func NewGetDeliveryJobCurrentCourierRequest(server string, deliveryJobUuid openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "delivery_job_uuid", runtime.ParamLocationPath, deliveryJobUuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/delivery-jobs/%s/couriers/current", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateOpenRobotLidCommandRequest calls the generic CreateOpenRobotLidCommand builder with application/json body
func NewCreateOpenRobotLidCommandRequest(server string, deliveryJobUuid openapi_types.UUID, body CreateOpenRobotLidCommandJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateOpenRobotLidCommandRequestWithBody(server, deliveryJobUuid, "application/json", bodyReader)
}

// NewCreateOpenRobotLidCommandRequestWithBody generates requests for CreateOpenRobotLidCommand with any type of body
func NewCreateOpenRobotLidCommandRequestWithBody(server string, deliveryJobUuid openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "delivery_job_uuid", runtime.ParamLocationPath, deliveryJobUuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/delivery-jobs/%s/couriers/current/open-lid", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostOrderDroppedOffRequest calls the generic PostOrderDroppedOff builder with application/json body
func NewPostOrderDroppedOffRequest(server string, deliveryJobUuid openapi_types.UUID, body PostOrderDroppedOffJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostOrderDroppedOffRequestWithBody(server, deliveryJobUuid, "application/json", bodyReader)
}

// NewPostOrderDroppedOffRequestWithBody generates requests for PostOrderDroppedOff with any type of body
func NewPostOrderDroppedOffRequestWithBody(server string, deliveryJobUuid openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "delivery_job_uuid", runtime.ParamLocationPath, deliveryJobUuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/delivery-jobs/%s/events/order-dropped-off", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostOrderPickedUpRequest calls the generic PostOrderPickedUp builder with application/json body
func NewPostOrderPickedUpRequest(server string, deliveryJobUuid openapi_types.UUID, body PostOrderPickedUpJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostOrderPickedUpRequestWithBody(server, deliveryJobUuid, "application/json", bodyReader)
}

// NewPostOrderPickedUpRequestWithBody generates requests for PostOrderPickedUp with any type of body
func NewPostOrderPickedUpRequestWithBody(server string, deliveryJobUuid openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "delivery_job_uuid", runtime.ParamLocationPath, deliveryJobUuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/delivery-jobs/%s/events/order-picked-up", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetOrderByExternalIdRequest generates requests for GetOrderByExternalId
func NewGetOrderByExternalIdRequest(server string, externalId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "external_id", runtime.ParamLocationPath, externalId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/external-ids/%s/order", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateOrderRequest calls the generic CreateOrder builder with application/json body
func NewCreateOrderRequest(server string, body CreateOrderJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateOrderRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateOrderRequestWithBody generates requests for CreateOrder with any type of body
func NewCreateOrderRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/orders")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetOrderRequest generates requests for GetOrder
func NewGetOrderRequest(server string, orderUuid openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "order_uuid", runtime.ParamLocationPath, orderUuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/orders/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetJobsForOrderRequest generates requests for GetJobsForOrder
func NewGetJobsForOrderRequest(server string, orderUuid openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "order_uuid", runtime.ParamLocationPath, orderUuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/orders/%s/delivery-jobs", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRequestQuoteRequest calls the generic RequestQuote builder with application/json body
func NewRequestQuoteRequest(server string, body RequestQuoteJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRequestQuoteRequestWithBody(server, "application/json", bodyReader)
}

// NewRequestQuoteRequestWithBody generates requests for RequestQuote with any type of body
func NewRequestQuoteRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/quotes")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewSetWebhooksRequest calls the generic SetWebhooks builder with application/json body
func NewSetWebhooksRequest(server string, body SetWebhooksJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSetWebhooksRequestWithBody(server, "application/json", bodyReader)
}

// NewSetWebhooksRequestWithBody generates requests for SetWebhooks with any type of body
func NewSetWebhooksRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/webhooks")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetDeliveryJob request
	GetDeliveryJobWithResponse(ctx context.Context, deliveryJobUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetDeliveryJobResponse, error)

	// PostJobCancelled request with any body
	PostJobCancelledWithBodyWithResponse(ctx context.Context, deliveryJobUuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostJobCancelledResponse, error)

	PostJobCancelledWithResponse(ctx context.Context, deliveryJobUuid openapi_types.UUID, body PostJobCancelledJSONRequestBody, reqEditors ...RequestEditorFn) (*PostJobCancelledResponse, error)

	// GetDeliveryJobCurrentCourier request
	GetDeliveryJobCurrentCourierWithResponse(ctx context.Context, deliveryJobUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetDeliveryJobCurrentCourierResponse, error)

	// CreateOpenRobotLidCommand request with any body
	CreateOpenRobotLidCommandWithBodyWithResponse(ctx context.Context, deliveryJobUuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateOpenRobotLidCommandResponse, error)

	CreateOpenRobotLidCommandWithResponse(ctx context.Context, deliveryJobUuid openapi_types.UUID, body CreateOpenRobotLidCommandJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateOpenRobotLidCommandResponse, error)

	// PostOrderDroppedOff request with any body
	PostOrderDroppedOffWithBodyWithResponse(ctx context.Context, deliveryJobUuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostOrderDroppedOffResponse, error)

	PostOrderDroppedOffWithResponse(ctx context.Context, deliveryJobUuid openapi_types.UUID, body PostOrderDroppedOffJSONRequestBody, reqEditors ...RequestEditorFn) (*PostOrderDroppedOffResponse, error)

	// PostOrderPickedUp request with any body
	PostOrderPickedUpWithBodyWithResponse(ctx context.Context, deliveryJobUuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostOrderPickedUpResponse, error)

	PostOrderPickedUpWithResponse(ctx context.Context, deliveryJobUuid openapi_types.UUID, body PostOrderPickedUpJSONRequestBody, reqEditors ...RequestEditorFn) (*PostOrderPickedUpResponse, error)

	// GetOrderByExternalId request
	GetOrderByExternalIdWithResponse(ctx context.Context, externalId string, reqEditors ...RequestEditorFn) (*GetOrderByExternalIdResponse, error)

	// CreateOrder request with any body
	CreateOrderWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateOrderResponse, error)

	CreateOrderWithResponse(ctx context.Context, body CreateOrderJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateOrderResponse, error)

	// GetOrder request
	GetOrderWithResponse(ctx context.Context, orderUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetOrderResponse, error)

	// GetJobsForOrder request
	GetJobsForOrderWithResponse(ctx context.Context, orderUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetJobsForOrderResponse, error)

	// RequestQuote request with any body
	RequestQuoteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RequestQuoteResponse, error)

	RequestQuoteWithResponse(ctx context.Context, body RequestQuoteJSONRequestBody, reqEditors ...RequestEditorFn) (*RequestQuoteResponse, error)

	// SetWebhooks request with any body
	SetWebhooksWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetWebhooksResponse, error)

	SetWebhooksWithResponse(ctx context.Context, body SetWebhooksJSONRequestBody, reqEditors ...RequestEditorFn) (*SetWebhooksResponse, error)
}

type GetDeliveryJobResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DeliveryJob
}

// Status returns HTTPResponse.Status
func (r GetDeliveryJobResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDeliveryJobResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostJobCancelledResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *InvalidClientActionError
}

// Status returns HTTPResponse.Status
func (r PostJobCancelledResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostJobCancelledResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetDeliveryJobCurrentCourierResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Courier
}

// Status returns HTTPResponse.Status
func (r GetDeliveryJobCurrentCourierResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDeliveryJobCurrentCourierResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateOpenRobotLidCommandResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *InvalidClientActionError
}

// Status returns HTTPResponse.Status
func (r CreateOpenRobotLidCommandResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateOpenRobotLidCommandResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostOrderDroppedOffResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *InvalidClientActionError
}

// Status returns HTTPResponse.Status
func (r PostOrderDroppedOffResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostOrderDroppedOffResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostOrderPickedUpResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *InvalidClientActionError
}

// Status returns HTTPResponse.Status
func (r PostOrderPickedUpResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostOrderPickedUpResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetOrderByExternalIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DeliveryOrder
}

// Status returns HTTPResponse.Status
func (r GetOrderByExternalIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetOrderByExternalIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateOrderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DeliveryOrder
	JSON400      *CreateOrderClientErrorResponse
}

// Status returns HTTPResponse.Status
func (r CreateOrderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateOrderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetOrderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DeliveryOrder
}

// Status returns HTTPResponse.Status
func (r GetOrderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetOrderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetJobsForOrderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]DeliveryJob
}

// Status returns HTTPResponse.Status
func (r GetJobsForOrderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetJobsForOrderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RequestQuoteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DeliveryOrderQuote
	JSON400      *RequestQuoteClientErrorResponse
}

// Status returns HTTPResponse.Status
func (r RequestQuoteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RequestQuoteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SetWebhooksResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Webhooks
	JSON400      *SetWebhookError
}

// Status returns HTTPResponse.Status
func (r SetWebhooksResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SetWebhooksResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetDeliveryJobWithResponse request returning *GetDeliveryJobResponse
func (c *ClientWithResponses) GetDeliveryJobWithResponse(ctx context.Context, deliveryJobUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetDeliveryJobResponse, error) {
	rsp, err := c.GetDeliveryJob(ctx, deliveryJobUuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDeliveryJobResponse(rsp)
}

// PostJobCancelledWithBodyWithResponse request with arbitrary body returning *PostJobCancelledResponse
func (c *ClientWithResponses) PostJobCancelledWithBodyWithResponse(ctx context.Context, deliveryJobUuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostJobCancelledResponse, error) {
	rsp, err := c.PostJobCancelledWithBody(ctx, deliveryJobUuid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostJobCancelledResponse(rsp)
}

func (c *ClientWithResponses) PostJobCancelledWithResponse(ctx context.Context, deliveryJobUuid openapi_types.UUID, body PostJobCancelledJSONRequestBody, reqEditors ...RequestEditorFn) (*PostJobCancelledResponse, error) {
	rsp, err := c.PostJobCancelled(ctx, deliveryJobUuid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostJobCancelledResponse(rsp)
}

// GetDeliveryJobCurrentCourierWithResponse request returning *GetDeliveryJobCurrentCourierResponse
func (c *ClientWithResponses) GetDeliveryJobCurrentCourierWithResponse(ctx context.Context, deliveryJobUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetDeliveryJobCurrentCourierResponse, error) {
	rsp, err := c.GetDeliveryJobCurrentCourier(ctx, deliveryJobUuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDeliveryJobCurrentCourierResponse(rsp)
}

// CreateOpenRobotLidCommandWithBodyWithResponse request with arbitrary body returning *CreateOpenRobotLidCommandResponse
func (c *ClientWithResponses) CreateOpenRobotLidCommandWithBodyWithResponse(ctx context.Context, deliveryJobUuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateOpenRobotLidCommandResponse, error) {
	rsp, err := c.CreateOpenRobotLidCommandWithBody(ctx, deliveryJobUuid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateOpenRobotLidCommandResponse(rsp)
}

func (c *ClientWithResponses) CreateOpenRobotLidCommandWithResponse(ctx context.Context, deliveryJobUuid openapi_types.UUID, body CreateOpenRobotLidCommandJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateOpenRobotLidCommandResponse, error) {
	rsp, err := c.CreateOpenRobotLidCommand(ctx, deliveryJobUuid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateOpenRobotLidCommandResponse(rsp)
}

// PostOrderDroppedOffWithBodyWithResponse request with arbitrary body returning *PostOrderDroppedOffResponse
func (c *ClientWithResponses) PostOrderDroppedOffWithBodyWithResponse(ctx context.Context, deliveryJobUuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostOrderDroppedOffResponse, error) {
	rsp, err := c.PostOrderDroppedOffWithBody(ctx, deliveryJobUuid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostOrderDroppedOffResponse(rsp)
}

func (c *ClientWithResponses) PostOrderDroppedOffWithResponse(ctx context.Context, deliveryJobUuid openapi_types.UUID, body PostOrderDroppedOffJSONRequestBody, reqEditors ...RequestEditorFn) (*PostOrderDroppedOffResponse, error) {
	rsp, err := c.PostOrderDroppedOff(ctx, deliveryJobUuid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostOrderDroppedOffResponse(rsp)
}

// PostOrderPickedUpWithBodyWithResponse request with arbitrary body returning *PostOrderPickedUpResponse
func (c *ClientWithResponses) PostOrderPickedUpWithBodyWithResponse(ctx context.Context, deliveryJobUuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostOrderPickedUpResponse, error) {
	rsp, err := c.PostOrderPickedUpWithBody(ctx, deliveryJobUuid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostOrderPickedUpResponse(rsp)
}

func (c *ClientWithResponses) PostOrderPickedUpWithResponse(ctx context.Context, deliveryJobUuid openapi_types.UUID, body PostOrderPickedUpJSONRequestBody, reqEditors ...RequestEditorFn) (*PostOrderPickedUpResponse, error) {
	rsp, err := c.PostOrderPickedUp(ctx, deliveryJobUuid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostOrderPickedUpResponse(rsp)
}

// GetOrderByExternalIdWithResponse request returning *GetOrderByExternalIdResponse
func (c *ClientWithResponses) GetOrderByExternalIdWithResponse(ctx context.Context, externalId string, reqEditors ...RequestEditorFn) (*GetOrderByExternalIdResponse, error) {
	rsp, err := c.GetOrderByExternalId(ctx, externalId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetOrderByExternalIdResponse(rsp)
}

// CreateOrderWithBodyWithResponse request with arbitrary body returning *CreateOrderResponse
func (c *ClientWithResponses) CreateOrderWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateOrderResponse, error) {
	rsp, err := c.CreateOrderWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateOrderResponse(rsp)
}

func (c *ClientWithResponses) CreateOrderWithResponse(ctx context.Context, body CreateOrderJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateOrderResponse, error) {
	rsp, err := c.CreateOrder(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateOrderResponse(rsp)
}

// GetOrderWithResponse request returning *GetOrderResponse
func (c *ClientWithResponses) GetOrderWithResponse(ctx context.Context, orderUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetOrderResponse, error) {
	rsp, err := c.GetOrder(ctx, orderUuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetOrderResponse(rsp)
}

// GetJobsForOrderWithResponse request returning *GetJobsForOrderResponse
func (c *ClientWithResponses) GetJobsForOrderWithResponse(ctx context.Context, orderUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetJobsForOrderResponse, error) {
	rsp, err := c.GetJobsForOrder(ctx, orderUuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetJobsForOrderResponse(rsp)
}

// RequestQuoteWithBodyWithResponse request with arbitrary body returning *RequestQuoteResponse
func (c *ClientWithResponses) RequestQuoteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RequestQuoteResponse, error) {
	rsp, err := c.RequestQuoteWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRequestQuoteResponse(rsp)
}

func (c *ClientWithResponses) RequestQuoteWithResponse(ctx context.Context, body RequestQuoteJSONRequestBody, reqEditors ...RequestEditorFn) (*RequestQuoteResponse, error) {
	rsp, err := c.RequestQuote(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRequestQuoteResponse(rsp)
}

// SetWebhooksWithBodyWithResponse request with arbitrary body returning *SetWebhooksResponse
func (c *ClientWithResponses) SetWebhooksWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetWebhooksResponse, error) {
	rsp, err := c.SetWebhooksWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetWebhooksResponse(rsp)
}

func (c *ClientWithResponses) SetWebhooksWithResponse(ctx context.Context, body SetWebhooksJSONRequestBody, reqEditors ...RequestEditorFn) (*SetWebhooksResponse, error) {
	rsp, err := c.SetWebhooks(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetWebhooksResponse(rsp)
}

// ParseGetDeliveryJobResponse parses an HTTP response from a GetDeliveryJobWithResponse call
func ParseGetDeliveryJobResponse(rsp *http.Response) (*GetDeliveryJobResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDeliveryJobResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DeliveryJob
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostJobCancelledResponse parses an HTTP response from a PostJobCancelledWithResponse call
func ParsePostJobCancelledResponse(rsp *http.Response) (*PostJobCancelledResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostJobCancelledResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest InvalidClientActionError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseGetDeliveryJobCurrentCourierResponse parses an HTTP response from a GetDeliveryJobCurrentCourierWithResponse call
func ParseGetDeliveryJobCurrentCourierResponse(rsp *http.Response) (*GetDeliveryJobCurrentCourierResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDeliveryJobCurrentCourierResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Courier
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateOpenRobotLidCommandResponse parses an HTTP response from a CreateOpenRobotLidCommandWithResponse call
func ParseCreateOpenRobotLidCommandResponse(rsp *http.Response) (*CreateOpenRobotLidCommandResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateOpenRobotLidCommandResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest InvalidClientActionError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParsePostOrderDroppedOffResponse parses an HTTP response from a PostOrderDroppedOffWithResponse call
func ParsePostOrderDroppedOffResponse(rsp *http.Response) (*PostOrderDroppedOffResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostOrderDroppedOffResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest InvalidClientActionError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParsePostOrderPickedUpResponse parses an HTTP response from a PostOrderPickedUpWithResponse call
func ParsePostOrderPickedUpResponse(rsp *http.Response) (*PostOrderPickedUpResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostOrderPickedUpResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest InvalidClientActionError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseGetOrderByExternalIdResponse parses an HTTP response from a GetOrderByExternalIdWithResponse call
func ParseGetOrderByExternalIdResponse(rsp *http.Response) (*GetOrderByExternalIdResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetOrderByExternalIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DeliveryOrder
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateOrderResponse parses an HTTP response from a CreateOrderWithResponse call
func ParseCreateOrderResponse(rsp *http.Response) (*CreateOrderResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateOrderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DeliveryOrder
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest CreateOrderClientErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseGetOrderResponse parses an HTTP response from a GetOrderWithResponse call
func ParseGetOrderResponse(rsp *http.Response) (*GetOrderResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetOrderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DeliveryOrder
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetJobsForOrderResponse parses an HTTP response from a GetJobsForOrderWithResponse call
func ParseGetJobsForOrderResponse(rsp *http.Response) (*GetJobsForOrderResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetJobsForOrderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []DeliveryJob
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseRequestQuoteResponse parses an HTTP response from a RequestQuoteWithResponse call
func ParseRequestQuoteResponse(rsp *http.Response) (*RequestQuoteResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RequestQuoteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DeliveryOrderQuote
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest RequestQuoteClientErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseSetWebhooksResponse parses an HTTP response from a SetWebhooksWithResponse call
func ParseSetWebhooksResponse(rsp *http.Response) (*SetWebhooksResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SetWebhooksResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Webhooks
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest SetWebhookError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}
