// Package delivery_sdk provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.10.1 DO NOT EDIT.
package delivery_sdk

import (
	"time"

	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for CourierState.
const (
	CourierStateAnalyzingDeliveryOffer CourierState = "analyzing-delivery-offer"

	CourierStateEnRouteToDropOff CourierState = "en-route-to-drop-off"

	CourierStateEnRouteToPickUp CourierState = "en-route-to-pick-up"

	CourierStatePlanningDropOffRoute CourierState = "planning-drop-off-route"

	CourierStatePlanningPickUpRoute CourierState = "planning-pick-up-route"

	CourierStateUnspecified CourierState = "unspecified"

	CourierStateWaitingForDropOff CourierState = "waiting-for-drop-off"

	CourierStateWaitingForPickUp CourierState = "waiting-for-pick-up"

	CourierStateWaitingToHandOver CourierState = "waiting-to-hand-over"
)

// Defines values for CourierType.
const (
	CourierTypeConventional CourierType = "conventional"

	CourierTypeRobot CourierType = "robot"
)

// Defines values for CourierEventKind.
const (
	CourierEventKindCourierAbortedDelivery CourierEventKind = "courier-aborted-delivery"

	CourierEventKindCourierAcceptedDeliveryOffer CourierEventKind = "courier-accepted-delivery-offer"

	CourierEventKindCourierArrivedAtDropOff CourierEventKind = "courier-arrived-at-drop-off"

	CourierEventKindCourierArrivedAtPickUp CourierEventKind = "courier-arrived-at-pick-up"

	CourierEventKindCourierDelegatedActiveDelivery CourierEventKind = "courier-delegated-active-delivery"

	CourierEventKindCourierDroppedOffPackage CourierEventKind = "courier-dropped-off-package"

	CourierEventKindCourierHandedOverPackage CourierEventKind = "courier-handed-over-package"

	CourierEventKindCourierLeftForDropOff CourierEventKind = "courier-left-for-drop-off"

	CourierEventKindCourierLeftForPickUp CourierEventKind = "courier-left-for-pick-up"

	CourierEventKindCourierPickedUpPackage CourierEventKind = "courier-picked-up-package"

	CourierEventKindCourierPositionChanged CourierEventKind = "courier-position-changed"

	CourierEventKindCourierPreparedToHandOver CourierEventKind = "courier-prepared-to-hand-over"

	CourierEventKindCourierReceivedDeliveryOffer CourierEventKind = "courier-received-delivery-offer"

	CourierEventKindCourierRejectedDeliveryOffer CourierEventKind = "courier-rejected-delivery-offer"

	CourierEventKindCourierStartedAcceptingDeliveries CourierEventKind = "courier-started-accepting-deliveries"

	CourierEventKindCourierStoppedAcceptingDeliveries CourierEventKind = "courier-stopped-accepting-deliveries"
)

// Defines values for DeliveryJobPackageHolder.
const (
	DeliveryJobPackageHolderCourier DeliveryJobPackageHolder = "courier"

	DeliveryJobPackageHolderReceiver DeliveryJobPackageHolder = "receiver"

	DeliveryJobPackageHolderShipper DeliveryJobPackageHolder = "shipper"

	DeliveryJobPackageHolderUnknown DeliveryJobPackageHolder = "unknown"
)

// Defines values for DeliveryJobStage.
const (
	DeliveryJobStageCourierAssignment DeliveryJobStage = "courier-assignment"

	DeliveryJobStageDeliveryCanceled DeliveryJobStage = "delivery-canceled"

	DeliveryJobStageDeliveryCompleted DeliveryJobStage = "delivery-completed"

	DeliveryJobStageDropOff DeliveryJobStage = "drop-off"

	DeliveryJobStagePickUp DeliveryJobStage = "pick-up"
)

// Defines values for DeliveryJobEventKind.
const (
	DeliveryJobEventKindDeliveryCanceled DeliveryJobEventKind = "delivery-canceled"

	DeliveryJobEventKindDeliveryCompleted DeliveryJobEventKind = "delivery-completed"

	DeliveryJobEventKindDeliveryHandedOver DeliveryJobEventKind = "delivery-handed-over"

	DeliveryJobEventKindDeliveryJobAcceptedByNextCourier DeliveryJobEventKind = "delivery-job-accepted-by-next-courier"

	DeliveryJobEventKindDeliveryJobAssigned DeliveryJobEventKind = "delivery-job-assigned"

	DeliveryJobEventKindDeliveryJobCreated DeliveryJobEventKind = "delivery-job-created"

	DeliveryJobEventKindDeliveryJobDelegatedToNextCourier DeliveryJobEventKind = "delivery-job-delegated-to-next-courier"

	DeliveryJobEventKindDeliveryJobOfferedToCourier DeliveryJobEventKind = "delivery-job-offered-to-courier"

	DeliveryJobEventKindDeliveryJobOfferedToNextCourier DeliveryJobEventKind = "delivery-job-offered-to-next-courier"

	DeliveryJobEventKindDeliveryJobRejectedByCourier DeliveryJobEventKind = "delivery-job-rejected-by-courier"

	DeliveryJobEventKindDeliveryJobRejectedByNextCourier DeliveryJobEventKind = "delivery-job-rejected-by-next-courier"

	DeliveryJobEventKindDeliveryJobUnassigned DeliveryJobEventKind = "delivery-job-unassigned"

	DeliveryJobEventKindDeliveryPickedUp DeliveryJobEventKind = "delivery-picked-up"

	DeliveryJobEventKindReceivedNewCourierPosition DeliveryJobEventKind = "received-new-courier-position"

	DeliveryJobEventKindUnassignedNextCourier DeliveryJobEventKind = "unassigned-next-courier"
)

// Defines values for DeliveryOrderStatus.
const (
	DeliveryOrderStatusOrderAccepted DeliveryOrderStatus = "order-accepted"

	DeliveryOrderStatusOrderCanceled DeliveryOrderStatus = "order-canceled"

	DeliveryOrderStatusOrderReceived DeliveryOrderStatus = "order-received"

	DeliveryOrderStatusOrderRejected DeliveryOrderStatus = "order-rejected"
)

// Defines values for DeliveryOrderRejectionReason.
const (
	DeliveryOrderRejectionReasonDeliveryDistanceTooLarge DeliveryOrderRejectionReason = "delivery-distance-too-large"

	DeliveryOrderRejectionReasonDropOffOutsideDeliveryArea DeliveryOrderRejectionReason = "drop-off-outside-delivery-area"

	DeliveryOrderRejectionReasonNoCapacity DeliveryOrderRejectionReason = "no-capacity"

	DeliveryOrderRejectionReasonOutsideDeliveryArea DeliveryOrderRejectionReason = "outside-delivery-area"

	DeliveryOrderRejectionReasonPickUpOutsideDeliveryArea DeliveryOrderRejectionReason = "pick-up-outside-delivery-area"

	DeliveryOrderRejectionReasonScheduledDeliveryNotSupported DeliveryOrderRejectionReason = "scheduled-delivery-not-supported"
)

// Defines values for InvalidClientActionErrorReason.
const (
	InvalidClientActionErrorReasonDeactivatedClient InvalidClientActionErrorReason = "deactivated-client"

	InvalidClientActionErrorReasonInvalidArgument InvalidClientActionErrorReason = "invalid-argument"

	InvalidClientActionErrorReasonSelfServiceUnavailable InvalidClientActionErrorReason = "self-service-unavailable"
)

// Defines values for SetWebhookErrorReason.
const (
	SetWebhookErrorReasonInvalidUrl SetWebhookErrorReason = "invalid-url"
)

// AddressDescription defines model for AddressDescription.
type AddressDescription struct {
	AddressLine1      string  `json:"addressLine1"`
	AddressLine2      *string `json:"addressLine2,omitempty"`
	Country           string  `json:"country"`
	EstablishmentName *string `json:"establishmentName,omitempty"`
	Locality          string  `json:"locality"`
	PostalCode        string  `json:"postalCode"`
	State             string  `json:"state"`
}

// CompleteAddress defines model for CompleteAddress.
type CompleteAddress struct {
	AddressDescription AddressDescription `json:"addressDescription"`
	GeocodedAddress    GeocodedAddress    `json:"geocodedAddress"`
}

// Courier defines model for Courier.
type Courier struct {
	ActiveDeliveryUuid    openapi_types.UUID  `json:"activeDeliveryUuid"`
	Destination           *CourierDestination `json:"destination,omitempty"`
	IsAcceptingDeliveries bool                `json:"isAcceptingDeliveries"`
	LastKnownPosition     *GeocodeLogEntry    `json:"lastKnownPosition,omitempty"`
	Name                  string              `json:"name"`
	State                 CourierState        `json:"state"`
	Type                  CourierType         `json:"type"`
	Uuid                  openapi_types.UUID  `json:"uuid"`
}

// CourierState defines model for Courier.State.
type CourierState string

// CourierType defines model for Courier.Type.
type CourierType string

// CourierDestination defines model for CourierDestination.
type CourierDestination struct {
	Eta             *time.Time      `json:"eta,omitempty"`
	GeocodedAddress GeocodedAddress `json:"geocodedAddress"`
}

// CourierEvent defines model for CourierEvent.
type CourierEvent struct {
	Courier       Courier            `json:"courier"`
	CourierBefore *Courier           `json:"courierBefore,omitempty"`
	Kind          CourierEventKind   `json:"kind"`
	ProducedAt    time.Time          `json:"producedAt"`
	Uuid          openapi_types.UUID `json:"uuid"`
}

// CourierEventKind defines model for CourierEvent.Kind.
type CourierEventKind string

// CreateOrderClientErrorResponse defines model for CreateOrderClientErrorResponse.
type CreateOrderClientErrorResponse interface{}

// DeliveryCharges defines model for DeliveryCharges.
type DeliveryCharges struct {
	TotalInCents int32 `json:"totalInCents"`
}

// DeliveryJob defines model for DeliveryJob.
type DeliveryJob struct {
	CompletedAt        *time.Time               `json:"completedAt,omitempty"`
	CurrentCourierUUID *openapi_types.UUID      `json:"currentCourierUUID,omitempty"`
	DeliveryCharges    DeliveryCharges          `json:"deliveryCharges"`
	DeliveryOrderUUID  openapi_types.UUID       `json:"deliveryOrderUUID"`
	DropOffAddress     CompleteAddress          `json:"dropOffAddress"`
	DropOffEstimatedAt time.Time                `json:"dropOffEstimatedAt"`
	NextCourierUUID    *openapi_types.UUID      `json:"nextCourierUUID,omitempty"`
	PackageHolder      DeliveryJobPackageHolder `json:"packageHolder"`
	PickUpAddress      CompleteAddress          `json:"pickUpAddress"`
	PickUpEstimatedAt  time.Time                `json:"pickUpEstimatedAt"`
	Stage              DeliveryJobStage         `json:"stage"`
	Uuid               openapi_types.UUID       `json:"uuid"`
}

// DeliveryJobPackageHolder defines model for DeliveryJob.PackageHolder.
type DeliveryJobPackageHolder string

// DeliveryJobStage defines model for DeliveryJob.Stage.
type DeliveryJobStage string

// DeliveryJobEvent defines model for DeliveryJobEvent.
type DeliveryJobEvent struct {
	DeliveryJob       DeliveryJob          `json:"deliveryJob"`
	DeliveryJobBefore *DeliveryJob         `json:"deliveryJobBefore,omitempty"`
	Kind              DeliveryJobEventKind `json:"kind"`
	ProducedAt        time.Time            `json:"producedAt"`
	Uuid              openapi_types.UUID   `json:"uuid"`
}

// DeliveryJobEventKind defines model for DeliveryJobEvent.Kind.
type DeliveryJobEventKind string

// DeliveryOrder defines model for DeliveryOrder.
type DeliveryOrder struct {
	DeliveryCharges DeliveryCharges     `json:"deliveryCharges"`
	DropOff         DeliveryService     `json:"dropOff"`
	ExternalID      string              `json:"externalID"`
	IsMock          bool                `json:"isMock"`
	PickUp          DeliveryService     `json:"pickUp"`
	ReceivedAt      time.Time           `json:"receivedAt"`
	Receiver        DeliveryOrderParty  `json:"receiver"`
	Shipper         DeliveryOrderParty  `json:"shipper"`
	Status          DeliveryOrderStatus `json:"status"`
	Uuid            openapi_types.UUID  `json:"uuid"`
}

// DeliveryOrderStatus defines model for DeliveryOrder.Status.
type DeliveryOrderStatus string

// DeliveryOrderCreationRequest defines model for DeliveryOrderCreationRequest.
type DeliveryOrderCreationRequest struct {
	DropOffAddress     CompleteAddress             `json:"dropOffAddress"`
	DropOffDeadlineAt  *time.Time                  `json:"dropOffDeadlineAt,omitempty"`
	DropOffNotes       *string                     `json:"dropOffNotes,omitempty"`
	DropOffNotifyParty *DeliveryServiceNotifyParty `json:"dropOffNotifyParty,omitempty"`
	ExternalID         string                      `json:"externalID"`
	IsMock             *bool                       `json:"isMock,omitempty"`
	PickUpAddress      CompleteAddress             `json:"pickUpAddress"`
	PickUpDeadlineAt   *time.Time                  `json:"pickUpDeadlineAt,omitempty"`
	PickUpNotes        *string                     `json:"pickUpNotes,omitempty"`
	PickUpNotifyParty  *DeliveryServiceNotifyParty `json:"pickUpNotifyParty,omitempty"`
	Receiver           DeliveryOrderParty          `json:"receiver"`
	Shipper            DeliveryOrderParty          `json:"shipper"`
}

// DeliveryOrderParty defines model for DeliveryOrderParty.
type DeliveryOrderParty struct {
	Email       *string `json:"email,omitempty"`
	IsBusiness  bool    `json:"isBusiness"`
	Name        string  `json:"name"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
}

// DeliveryOrderQuote defines model for DeliveryOrderQuote.
type DeliveryOrderQuote struct {
	DeliveryCharges        DeliveryCharges    `json:"deliveryCharges"`
	DropOffAddress         CompleteAddress    `json:"dropOffAddress"`
	DropOffAfter           time.Time          `json:"dropOffAfter"`
	DropOffDeadlineAt      time.Time          `json:"dropOffDeadlineAt"`
	EstimatedDropOffWindow TimeWindow         `json:"estimatedDropOffWindow"`
	EstimatedPickUpWindow  TimeWindow         `json:"estimatedPickUpWindow"`
	GoodUntil              time.Time          `json:"goodUntil"`
	IsMock                 bool               `json:"isMock"`
	PickUpAddress          CompleteAddress    `json:"pickUpAddress"`
	PickUpAfter            time.Time          `json:"pickUpAfter"`
	PickUpDeadlineAt       time.Time          `json:"pickUpDeadlineAt"`
	ReceivedAt             time.Time          `json:"receivedAt"`
	Uuid                   openapi_types.UUID `json:"uuid"`
}

// DeliveryOrderQuoteRequest defines model for DeliveryOrderQuoteRequest.
type DeliveryOrderQuoteRequest struct {
	DropOffAddress GeocodedAddress `json:"dropOffAddress"`
	IsMock         *bool           `json:"isMock,omitempty"`
	PickUpAddress  GeocodedAddress `json:"pickUpAddress"`
}

// DeliveryOrderRejection defines model for DeliveryOrderRejection.
type DeliveryOrderRejection struct {
	Message string                       `json:"message"`
	Reason  DeliveryOrderRejectionReason `json:"reason"`
}

// DeliveryOrderRejectionReason defines model for DeliveryOrderRejection.Reason.
type DeliveryOrderRejectionReason string

// DeliveryService defines model for DeliveryService.
type DeliveryService struct {
	Address                CompleteAddress            `json:"address"`
	DeadlineAt             time.Time                  `json:"deadlineAt"`
	IsSelfServiceAvailable bool                       `json:"isSelfServiceAvailable"`
	Notes                  string                     `json:"notes"`
	NotifyParty            DeliveryServiceNotifyParty `json:"notifyParty"`
	ServiceAfter           time.Time                  `json:"serviceAfter"`
}

// DeliveryServiceNotifyParty defines model for DeliveryServiceNotifyParty.
type DeliveryServiceNotifyParty struct {
	Email       *string `json:"email,omitempty"`
	Name        *string `json:"name,omitempty"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
}

// GeocodeLogEntry defines model for GeocodeLogEntry.
type GeocodeLogEntry struct {
	GeocodedAddress GeocodedAddress `json:"geocodedAddress"`
	RecordedAt      time.Time       `json:"recordedAt"`
}

// GeocodedAddress defines model for GeocodedAddress.
type GeocodedAddress struct {
	GooglePlaceID *string `json:"googlePlaceID,omitempty"`
	Lat           float64 `json:"lat"`
	Lng           float64 `json:"lng"`
}

// InvalidClientActionError defines model for InvalidClientActionError.
type InvalidClientActionError struct {
	Message string                         `json:"message"`
	Reason  InvalidClientActionErrorReason `json:"reason"`
}

// InvalidClientActionErrorReason defines model for InvalidClientActionError.Reason.
type InvalidClientActionErrorReason string

// RequestQuoteClientErrorResponse defines model for RequestQuoteClientErrorResponse.
type RequestQuoteClientErrorResponse interface{}

// SetWebhookError defines model for SetWebhookError.
type SetWebhookError struct {
	Message string                `json:"message"`
	Reason  SetWebhookErrorReason `json:"reason"`
}

// SetWebhookErrorReason defines model for SetWebhookError.Reason.
type SetWebhookErrorReason string

// TimeWindow defines model for TimeWindow.
type TimeWindow struct {
	From  time.Time `json:"from"`
	Until time.Time `json:"until"`
}

// Webhook defines model for Webhook.
type Webhook struct {
	ApiKey string `json:"api_key"`
	Url    string `json:"url"`
}

// Webhooks defines model for Webhooks.
type Webhooks struct {
	CourierEvents     Webhook `json:"courierEvents"`
	DeliveryJobEvents Webhook `json:"deliveryJobEvents"`
}

// PostJobCancelledJSONBody defines parameters for PostJobCancelled.
type PostJobCancelledJSONBody interface{}

// CreateOpenRobotLidCommandJSONBody defines parameters for CreateOpenRobotLidCommand.
type CreateOpenRobotLidCommandJSONBody interface{}

// PostOrderDroppedOffJSONBody defines parameters for PostOrderDroppedOff.
type PostOrderDroppedOffJSONBody interface{}

// PostOrderPickedUpJSONBody defines parameters for PostOrderPickedUp.
type PostOrderPickedUpJSONBody interface{}

// CreateOrderJSONBody defines parameters for CreateOrder.
type CreateOrderJSONBody DeliveryOrderCreationRequest

// RequestQuoteJSONBody defines parameters for RequestQuote.
type RequestQuoteJSONBody DeliveryOrderQuoteRequest

// SetWebhooksJSONBody defines parameters for SetWebhooks.
type SetWebhooksJSONBody Webhooks

// PostJobCancelledJSONRequestBody defines body for PostJobCancelled for application/json ContentType.
type PostJobCancelledJSONRequestBody PostJobCancelledJSONBody

// CreateOpenRobotLidCommandJSONRequestBody defines body for CreateOpenRobotLidCommand for application/json ContentType.
type CreateOpenRobotLidCommandJSONRequestBody CreateOpenRobotLidCommandJSONBody

// PostOrderDroppedOffJSONRequestBody defines body for PostOrderDroppedOff for application/json ContentType.
type PostOrderDroppedOffJSONRequestBody PostOrderDroppedOffJSONBody

// PostOrderPickedUpJSONRequestBody defines body for PostOrderPickedUp for application/json ContentType.
type PostOrderPickedUpJSONRequestBody PostOrderPickedUpJSONBody

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody CreateOrderJSONBody

// RequestQuoteJSONRequestBody defines body for RequestQuote for application/json ContentType.
type RequestQuoteJSONRequestBody RequestQuoteJSONBody

// SetWebhooksJSONRequestBody defines body for SetWebhooks for application/json ContentType.
type SetWebhooksJSONRequestBody SetWebhooksJSONBody
